apiVersion: rabbitmq.com/v1beta1
kind: Permission
metadata:
  name: rabbit-user1-test-permission
spec:
  vhost: "test"
  user: "user1" # name of the RabbitMQ user
  permissions:
    write: ".*"
    configure: ".*"
    read: ".*"
  rabbitmqClusterReference:
    name: rabbitmqcluster-sample
