---
apiVersion: v1
kind: Secret
metadata:
  name: my-user-credentials # IMPORTANT: this Secret name must match .spec.importCredentialsSecret.name field in User object
stringData:
  username: user1
  password: abc123
---
apiVersion: rabbitmq.com/v1beta1
kind: User
metadata:
  name: user1
spec:
  tags:
    - management # administrator, management, monitoring, policymaker, impersonator
  rabbitmqClusterReference:
    name: rabbitmqcluster-sample # rabbitmqCluster must exist in the same namespace as this resource
  importCredentialsSecret:
    name: my-user-credentials # must match the name of the Secret
